#!/usr/bin/env python3
"""
kit init — 自动分析项目，生成 CLAUDE.md 和 .claude/ 配置。

流程:
  1. 扫描项目结构，识别技术栈
  2. 生成 CLAUDE.md（项目上下文）
  3. 创建 .claude/ 目录骨架
  4. 输出 next steps
"""
import os
import sys
from pathlib import Path
from datetime import datetime


LANG_DETECT = {
    "pom.xml": ("Java", "Maven", "mvn"),
    "build.gradle": ("Java/Kotlin", "Gradle", "gradle"),
    "package.json": ("Node.js", "npm/yarn/pnpm", "npm"),
    "go.mod": ("Go", "Go Modules", "go"),
    "Cargo.toml": ("Rust", "Cargo", "cargo"),
    "requirements.txt": ("Python", "pip", "python"),
    "pyproject.toml": ("Python", "pip/poetry", "python"),
    "Gemfile": ("Ruby", "Bundler", "bundle"),
    "composer.json": ("PHP", "Composer", "composer"),
    "CMakeLists.txt": ("C/C++", "CMake", "cmake"),
}

FRAMEWORK_HINTS = {
    "spring": "Spring Boot",
    "django": "Django",
    "flask": "Flask",
    "fastapi": "FastAPI",
    "react": "React",
    "vue": "Vue.js",
    "angular": "Angular",
    "express": "Express",
    "next": "Next.js",
    "gin": "Gin",
    "echo": "Echo",
    "laravel": "Laravel",
    "rails": "Ruby on Rails",
}

IGNORE_DIRS = {".git", "node_modules", "__pycache__", ".idea", "dist", "build", "target", "vendor", ".venv"}


def find_root() -> Path:
    target = sys.argv[1] if len(sys.argv) > 1 else os.getcwd()
    return Path(target).resolve()


def detect_tech_stack(root: Path) -> dict:
    """扫描项目根目录，自动识别技术栈"""
    detected = {"language": "unknown", "build_tool": "unknown", "build_cmd": "", "frameworks": [], "dirs": []}

    for filename, (lang, build, cmd) in LANG_DETECT.items():
        if (root / filename).exists():
            detected["language"] = lang
            detected["build_tool"] = build
            detected["build_cmd"] = cmd
            break

    # 扫描框架线索
    for candidate in [root / "pom.xml", root / "build.gradle", root / "package.json", root / "go.mod"]:
        if candidate.exists():
            content = candidate.read_text(encoding="utf-8").lower()
            for hint, framework in FRAMEWORK_HINTS.items():
                if hint in content and framework not in detected["frameworks"]:
                    detected["frameworks"].append(framework)

    # 扫描关键目录
    dirs_output = []
    try:
        items = sorted(root.iterdir())
        for item in items:
            if item.name in IGNORE_DIRS or item.name.startswith("."):
                continue
            if item.is_dir():
                dirs_output.append(item.name)
    except PermissionError:
        pass
    detected["dirs"] = dirs_output[:20]

    return detected


def generate_claude_md(root: Path, tech: dict) -> str:
    project_name = root.name

    return f"""# {project_name}

<!-- Generated by kit init on {datetime.now().strftime("%Y-%m-%d %H:%M")} -->

## 技术栈

- 语言: {tech["language"]}
- 构建: {tech["build_tool"]}
{f"- 框架: {', '.join(tech['frameworks'])}" if tech["frameworks"] else ""}

## 构建命令

```bash
# 构建
{tech["build_cmd"]} build

# 测试
{tech["build_cmd"]} test
```

## 目录结构

```
{project_name}/
"""
    for d in tech["dirs"][:10]:
        generated_claude_md += f"├── {d}/\n"
    generated_claude_md += "└── ...\n"
    generated_claude_md += "```\n\n"

    generated_claude_md += """## 代码约定

<!-- TODO: 补充项目特有的代码规范、命名约定、架构决策 -->

## 注意事项

<!-- TODO: 补充已知陷阱、历史遗留问题 -->

## 相关文档

<!-- TODO: 补充项目设计文档、wiki 链接 -->
"""
    return generated_claude_md


def main():
    root = find_root()
    print(f"kit init: 分析项目 {root.name}...")

    tech = detect_tech_stack(root)
    print(f"  检测到: {tech['language']} / {tech['build_tool']}")
    if tech["frameworks"]:
        print(f"  框架: {', '.join(tech['frameworks'])}")

    # 生成 CLAUDE.md
    claude_md = generate_claude_md(root, tech)
    claude_path = root / "CLAUDE.md"
    if claude_path.exists():
        print(f"  ⚠ CLAUDE.md 已存在，跳过生成")
    else:
        claude_path.write_text(claude_md, encoding="utf-8")
        print(f"  ✅ CLAUDE.md 已生成")

    # 创建 .claude/ 目录
    claude_dir = root / ".claude"
    claude_dir.mkdir(exist_ok=True)
    (claude_dir / "settings.local.json").touch()
    print(f"  ✅ .claude/ 目录已创建")

    # Next steps
    print()
    print("下一步:")
    print(f"  1. 编辑 {claude_path} 补充项目特有信息")
    print(f"  2. 补充项目 CLAUDE.md 中的 TODO 项")
    print(f"  3. 运行 kit sync --from=xxx 同步团队共享配置")
    print(f"  4. 提交 CLAUDE.md 到仓库")


if __name__ == "__main__":
    main()
